/**
 * Created by xiaoding on 2016/2/19.
 */
enum BottomMenuType
{
	MENU_CALL_ROLL = 1,
	MENU_SNIPPING,
	MENU_COLOR,
	MENU_WORD,
	MENU_ERASER,
	MENU_CHOOSE,
	MENU_BOOK,
	MENU_CLOUD_DISK,
	MENU_HOUSE_WORK,
	MENU_SYNC_CLASS,
	MENU_STATISTIC,
	MENU_SAVE
}